'use strict';

document.refinedBitbucket = document.refinedBitbucket || {};

document.refinedBitbucket.languages = {
    ".groovy": "language-groovy",
    ".gradle": "language-groovy",
    ".bash": "language-bash",
    ".sh": "language-bash",
    ".jsp": "language-java",
    ".java": "language-java",
    ".xml": "language-markup",
    ".html": "language-markup",
    ".js": "language-javascript",
    ".css": "language-css",
    ".cs": "language-csharp",
    ".h": "language-c",
    ".c": "language-c",
    ".cpp": "language-cpp",
    ".coffee": "language-coffeescript",
    ".go": "language-go",
    ".hbs": "language-handlebars",
    ".handlebars": "language-handlebars",
    ".json": "language-json",
    ".less": "language-less",
    ".md": "language-markdown",
    ".py": "language-python",
    ".php": "language-php",
    ".phtml": "language-php",
    ".php3": "language-php",
    ".php4": "language-php",
    ".php5": "language-php",
    ".phps": "language-php",
    ".jsx": "language-jsx",
    ".rb": "language-ruby",
    ".sass": "language-sass",
    ".scss": "language-scss",
    ".sbt": "language-scala",
    ".scala": "language-scala",
    ".swift": "language-swift",
    ".yaml": "language-yaml"
};
